# fly.toml app configuration file generated for iccmobile on 2023-12-10T16:10:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iccmobile"
primary_region = "ord"
kill_signal = "SIGTERM"

[build]

[env]
  PHX_HOST = "iccmobile.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 2048
